github: [ronaldrp, anotheruser]
patreon: ronaldrp
open_collective: ronaldrp_project
ko_fi: ronaldrp
tidelift: npm/ronaldrp-package
community_bridge: ronaldrp-community
liberapay: ronaldrp
issuehunt: ronaldrp
lfx_crowdfunding: ronaldrp-crowdfunding
polar: ronaldrp
buy_me_a_coffee: ronaldrp
thanks_dev: ronaldrp
custom: ['https://example.com/donate', 'https://another-example.com/support']
